### PR TITLE
Build for ppc64le

### PR DESCRIPTION
**Pull request by willsALMANJ**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This adds a build for ppc64le.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by scopatz** [comment]
You should probably do this through the arch migrator. Just put in a PR that adds urwid to this file: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/arch_rebuild.txt

**Comment by willsALMANJ** [comment]
Okay, I created https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/544, but I don't follow what is going on between the two repos. Are packages listed in that file treated differently by conda-forge-linter when re-rendering the feedstock? Does this PR need to be modified?

I am partly asking because I want to make sure I do the right thing for this other PR I made to add ppc64le for another package: https://github.com/conda-forge/qutip-feedstock/pull/45, and I would like to update pudb to work on ppc64le as well (in that case, I think it is possible to switch to `noarch: python` rather than enable ppc64le though).

**Comment by scopatz** [comment]
Sorry, yeah I know the workflow isn't clear here.

The packages that are listed in that file are to-level pacakages that we want to migrate. The autotick bot (which runs once an hour, and is different from the linter bot) will read that file. It will then compute all the deps for every package in that list, figure out which packages from the total set of deps have or haven't been migrated to the new arches (power and arm) haven't been migrated yet, and then put in PRs enabling the next set of packages in the correct topological order.

This PR should be closed because the autotick bot doesn't know about it and would issue another enabling PR in the futurue.  Also, because the bot properly handles dependencies, it is always better to use the bot than putting these things in manually.  

If you want to know how the migration is going, you can always check out https://conda-forge.org/status/ page. Find the "aarm64 & ppc64le" entry in current migrations.  It is really helpful!

**Comment by scopatz** [comment]
Also note that the bot PR is here: https://github.com/conda-forge/urwid-feedstock/pull/13#issuecomment-612143544

**Comment by willsALMANJ** [comment]
Thanks for the explanation!

What about switching a package to noarch like I tried to do here: https://github.com/conda-forge/pudb-feedstock/pull/17? Should that not be done manually?

**Comment by scopatz** [comment]
Switching a package to noarch is a manual thing.  No bot for that (anymore?) :wink:

**Pull request closed without merging**
